# Generated by Django 5.1.2 on 2024-10-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoan',
            fields=[
                ('acc', models.IntegerField(primary_key='accno', serialize=False)),
                ('ph', models.IntegerField()),
                ('ifsc', models.CharField(max_length=100)),
                ('loanno', models.IntegerField()),
                ('adress', models.CharField(max_length=100)),
                ('pan', models.IntegerField()),
                ('adhar', models.IntegerField()),
            ],
        ),
    ]
